### ISSUE TITLE
Swift 2.0 Support

### ISSUE THREAD

**Issue by cjwirth** [KyoheiG3/Keynode#2]
プルリクはいい加減すぎたから、とりあえず Issue で

**Comment by KyoheiG3** [comment]
対応しました。
https://github.com/KyoheiG3/Keynode/tree/swift-2.0
ios9も、バグがあるけど動きます。

**Comment by KyoheiG3** [comment]
まだ`UITextView`は動かない・・・

**Comment by KyoheiG3** [comment]
対応しました。
